# Generated by Django 4.0.2 on 2022-02-11 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='res',
            field=models.TextField(null=True),
        ),
    ]
